-- classifieds seed — English-canonical taxonomy (codes = English slugs; labels = display).
-- Generated from frontend taxonomy/*.md (en) + ky-taxonomy.draft.json (ky). NO Russian.
-- Geo names transliterated to latin (native review welcome). Enum option KY is Phase 2.

PRAGMA foreign_keys = ON;

INSERT INTO geo_oblast (id, name, labels, sort_order) VALUES
  ('ob-bishkek', 'Bishkek', NULL, 0),
  ('ob-osh-city', 'Osh (city)', NULL, 1),
  ('ob-chuy', 'Chuy', NULL, 2),
  ('ob-osh', 'Osh', NULL, 3),
  ('ob-jalalabad', 'Jalal-Abad', NULL, 4),
  ('ob-issykkul', 'Issyk-Kul', NULL, 5),
  ('ob-naryn', 'Naryn', NULL, 6),
  ('ob-talas', 'Talas', NULL, 7),
  ('ob-batken', 'Batken', NULL, 8);

INSERT INTO geo_city (id, oblast_id, name, labels, sort_order) VALUES
  ('ci-bishkek', 'ob-bishkek', 'Bishkek', '{"ky": "Бишкек"}', 0),
  ('ci-osh', 'ob-osh-city', 'Osh', '{"ky": "Ош"}', 0),
  ('ci-tokmok', 'ob-chuy', 'Tokmok', '{"ky": "Токмок"}', 0),
  ('ci-uzgen', 'ob-osh', 'Uzgen', '{"ky": "Өзгөн"}', 0),
  ('ci-jalalabad', 'ob-jalalabad', 'Jalal-Abad', '{"ky": "Жалал-Абад"}', 0),
  ('ci-karakol', 'ob-issykkul', 'Karakol', '{"ky": "Каракол"}', 0),
  ('ci-naryn', 'ob-naryn', 'Naryn', '{"ky": "Нарын"}', 0),
  ('ci-talas', 'ob-talas', 'Talas', '{"ky": "Талас"}', 0),
  ('ci-batken', 'ob-batken', 'Batken', '{"ky": "Баткен"}', 0),
  ('ci-kara-balta', 'ob-chuy', 'Kara-Balta', '{"ky": "Кара-Балта"}', 1),
  ('ci-balykchy', 'ob-issykkul', 'Balykchy', '{"ky": "Балыкчы"}', 1),
  ('ci-kant', 'ob-chuy', 'Kant', '{"ky": "Кант"}', 2),
  ('ci-cholponata', 'ob-issykkul', 'Cholpon-Ata', '{"ky": "Чолпон-Ата"}', 2);

INSERT INTO geo_district (id, city_id, name, sort_order) VALUES
  ('di-leninsky', 'ci-bishkek', 'Leninsky', 0),
  ('di-oktyabrsky', 'ci-bishkek', 'Oktyabrsky', 1),
  ('di-pervomaysky', 'ci-bishkek', 'Pervomaysky', 2),
  ('di-sverdlovsky', 'ci-bishkek', 'Sverdlovsky', 3);

INSERT INTO category (id, parent_id, slug, name, labels, sort_order) VALUES
  ('cat-transport', NULL, 'transport', 'Transport', NULL, 0),
  ('cat-realestate', NULL, 'realestate', 'Real Estate', NULL, 1),
  ('cat-electronics', NULL, 'electronics', 'Electronics', NULL, 2),
  ('cat-home', NULL, 'home', 'Home & Garden', '{"ky": "Үй жана бак"}', 3),
  ('cat-personal', NULL, 'personal', 'Personal Items', '{"ky": "Жеке буюмдар"}', 4),
  ('cat-animals', NULL, 'animals', 'Animals', '{"ky": "Жаныбарлар"}', 5),
  ('cat-jobs', NULL, 'jobs', 'Jobs', '{"ky": "Жумуш"}', 6),
  ('cat-services', NULL, 'services', 'Services', '{"ky": "Кызматтар"}', 7),
  ('cat-cars', 'cat-transport', 'cars', 'Cars', '{"ky": "Автоунаалар"}', 0),
  ('cat-apartments', 'cat-realestate', 'apartments', 'Apartments', '{"ky": "Батирлер"}', 0),
  ('cat-phones', 'cat-electronics', 'phones', 'Phones', '{"ky": "Телефондор"}', 0),
  ('cat-furniture', 'cat-home', 'furniture', 'Furniture', '{"ky": "Эмерек"}', 0),
  ('cat-clothing', 'cat-personal', 'clothing', 'Clothing', '{"ky": "Кийим"}', 0),
  ('cat-dogs', 'cat-animals', 'dogs', 'Dogs', '{"ky": "Иттер"}', 0),
  ('cat-moto', 'cat-transport', 'moto', 'Motorcycles', '{"ky": "Мотоциклдер"}', 1),
  ('cat-houses', 'cat-realestate', 'houses', 'Houses', '{"ky": "Үйлөр"}', 1),
  ('cat-computers', 'cat-electronics', 'computers', 'Computers', '{"ky": "Компьютерлер"}', 1),
  ('cat-appliances', 'cat-home', 'appliances', 'Appliances', '{"ky": "Тиричилик техникасы"}', 1),
  ('cat-shoes', 'cat-personal', 'shoes', 'Shoes', '{"ky": "Бут кийим"}', 1),
  ('cat-cats', 'cat-animals', 'cats', 'Cats', '{"ky": "Мышыктар"}', 1),
  ('cat-trucks', 'cat-transport', 'trucks', 'Trucks & machinery', '{"ky": "Жүк унаалары жана атайын техника"}', 2),
  ('cat-commercial', 'cat-realestate', 'commercial', 'Commercial', '{"ky": "Коммерциялык кыймылсыз мүлк"}', 2),
  ('cat-tablets', 'cat-electronics', 'tablets', 'Tablets', '{"ky": "Планшеттер"}', 2),
  ('cat-build', 'cat-home', 'build', 'Repair & building materials', '{"ky": "Оңдоо жана курулуш материалдары"}', 2),
  ('cat-kids', 'cat-personal', 'kids', 'Kids', '{"ky": "Балдар товарлары"}', 2),
  ('cat-birds', 'cat-animals', 'birds', 'Birds', '{"ky": "Канаттуулар"}', 2),
  ('cat-parts', 'cat-transport', 'parts', 'Parts & accessories', '{"ky": "Тетиктер жана аксессуарлар"}', 3),
  ('cat-land', 'cat-realestate', 'land', 'Land', '{"ky": "Жер тилкелери"}', 3),
  ('cat-tv', 'cat-electronics', 'tv', 'TV & projectors', '{"ky": "ТВ жана проекторлор"}', 3),
  ('cat-plants', 'cat-home', 'plants', 'Plants', '{"ky": "Өсүмдүктөр"}', 3),
  ('cat-jewelry', 'cat-personal', 'jewelry', 'Watches & accessories', '{"ky": "Саат, зер буюмдары, аксессуарлар"}', 3),
  ('cat-pets-other', 'cat-animals', 'pets-other', 'Other animals', '{"ky": "Башка жаныбарлар"}', 3),
  ('cat-garages', 'cat-realestate', 'garages', 'Garages', '{"ky": "Гараждар жана токтотуучу жайлар"}', 4),
  ('cat-audio', 'cat-electronics', 'audio', 'Audio', '{"ky": "Аудио"}', 4),
  ('cat-homeware', 'cat-home', 'homeware', 'Homeware', '{"ky": "Идиш-аяк, текстиль, декор"}', 4),
  ('cat-beauty', 'cat-personal', 'beauty', 'Beauty & health', '{"ky": "Сулуулук жана ден соолук"}', 4),
  ('cat-pet-supplies', 'cat-animals', 'pet-supplies', 'Pet supplies', '{"ky": "Жаныбарлар үчүн товарлар"}', 4),
  ('cat-photo', 'cat-electronics', 'photo', 'Photo & video', '{"ky": "Фото жана видео"}', 5),
  ('cat-consoles', 'cat-electronics', 'consoles', 'Consoles', '{"ky": "Оюн приставкалары"}', 6),
  ('cat-smartwatch', 'cat-electronics', 'smartwatch', 'Smartwatches', '{"ky": "Акылдуу сааттар"}', 7);

INSERT INTO category_attribute (id, category_id, key, label, type, required, filterable, unit, options, depends_on, sort_order) VALUES
  ('ca-apt-deal', 'cat-apartments', 'deal', '{"en": "Listing type", "ky": "Бүтүм түрү"}', 'enum', 1, 1, NULL, '[{"code": "sale", "labels": {"en": "Sale"}}, {"code": "long-term-rent", "labels": {"en": "Long-term rent"}}, {"code": "daily-rent", "labels": {"en": "Daily rent"}}]', NULL, 0),
  ('ca-apt-rooms', 'cat-apartments', 'rooms', '{"en": "Rooms", "ky": "Бөлмө"}', 'int', 1, 1, NULL, NULL, NULL, 1),
  ('ca-apt-area', 'cat-apartments', 'area', '{"en": "Area", "ky": "Аянты"}', 'number', 0, 1, 'm²', NULL, NULL, 2),
  ('ca-apt-floor', 'cat-apartments', 'floor', '{"en": "Floor", "ky": "Кабат"}', 'int', 0, 1, NULL, NULL, NULL, 3),
  ('ca-apt-floors', 'cat-apartments', 'total_floors', '{"en": "Total floors", "ky": "Үйдүн кабаттыгы"}', 'int', 0, 0, NULL, NULL, NULL, 4),
  ('ca-apt-furn', 'cat-apartments', 'furnished', '{"en": "Furnished", "ky": "Эмерек"}', 'bool', 0, 1, NULL, NULL, NULL, 5),
  ('ca-appl-type', 'cat-appliances', 'appliance_type', '{"en": "Type", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "refrigerators", "labels": {"en": "Refrigerators"}}, {"code": "washers", "labels": {"en": "Washers"}}, {"code": "stoves", "labels": {"en": "Stoves"}}, {"code": "dishwashers", "labels": {"en": "Dishwashers"}}, {"code": "microwaves", "labels": {"en": "Microwaves"}}, {"code": "air-conditioners", "labels": {"en": "Air conditioners"}}, {"code": "vacuums", "labels": {"en": "Vacuums"}}]', NULL, 0),
  ('ca-audio-type', 'cat-audio', 'audio_type', '{"en": "Type", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "headphones", "labels": {"en": "Headphones"}}, {"code": "speakers", "labels": {"en": "Speakers"}}, {"code": "soundbar", "labels": {"en": "Soundbar"}}, {"code": "microphones", "labels": {"en": "Microphones"}}]', NULL, 0),
  ('ca-birds-breed', 'cat-birds', 'breed', '{"en": "Species", "ky": "Түрү"}', 'text', 0, 1, NULL, NULL, NULL, 0),
  ('ca-build-type', 'cat-build', 'build_type', '{"en": "Category", "ky": "Категория"}', 'enum', 0, 1, NULL, '[{"code": "tools", "labels": {"en": "Tools"}}, {"code": "building-materials", "labels": {"en": "Building materials"}}, {"code": "plumbing", "labels": {"en": "Plumbing"}}, {"code": "electrical", "labels": {"en": "Electrical"}}, {"code": "doors-and-windows", "labels": {"en": "Doors & windows"}}]', NULL, 0),
  ('ca-car-make', 'cat-cars', 'make', '{"en": "Make", "ky": "Марка"}', 'enum', 1, 1, NULL, '[{"code": "Toyota"}, {"code": "Honda"}, {"code": "Nissan"}, {"code": "Mercedes-Benz"}, {"code": "BMW"}, {"code": "Audi"}, {"code": "Lexus"}, {"code": "Hyundai"}, {"code": "Kia"}, {"code": "Lada"}, {"code": "Mitsubishi"}, {"code": "Volkswagen"}]', NULL, 0),
  ('ca-car-model', 'cat-cars', 'model', '{"en": "Model", "ky": "Модель"}', 'text', 0, 1, NULL, NULL, 'make', 1),
  ('ca-car-year', 'cat-cars', 'year', '{"en": "Year", "ky": "Чыгарылган жылы"}', 'int', 1, 1, NULL, NULL, NULL, 2),
  ('ca-car-mileage', 'cat-cars', 'mileage', '{"en": "Mileage", "ky": "Жүрүшү"}', 'int', 0, 1, 'km', NULL, NULL, 3),
  ('ca-car-trans', 'cat-cars', 'transmission', '{"en": "Transmission", "ky": "Берүү кутусу"}', 'enum', 0, 1, NULL, '[{"code": "manual", "labels": {"en": "Manual"}}, {"code": "automatic", "labels": {"en": "Automatic"}}, {"code": "cvt", "labels": {"en": "CVT"}}, {"code": "amt", "labels": {"en": "AMT"}}]', NULL, 4),
  ('ca-car-fuel', 'cat-cars', 'fuel', '{"en": "Fuel", "ky": "Күйүүчү май"}', 'enum', 0, 1, NULL, '[{"code": "petrol", "labels": {"en": "Petrol"}}, {"code": "diesel", "labels": {"en": "Diesel"}}, {"code": "lpg", "labels": {"en": "Gas"}}, {"code": "hybrid", "labels": {"en": "Hybrid"}}, {"code": "electric", "labels": {"en": "Electric"}}]', NULL, 5),
  ('ca-car-body', 'cat-cars', 'body', '{"en": "Body type", "ky": "Кузов"}', 'enum', 0, 1, NULL, '[{"code": "sedan", "labels": {"en": "Sedan"}}, {"code": "hatchback", "labels": {"en": "Hatchback"}}, {"code": "wagon", "labels": {"en": "Wagon"}}, {"code": "suv", "labels": {"en": "SUV"}}, {"code": "minivan", "labels": {"en": "Minivan"}}, {"code": "coupe", "labels": {"en": "Coupe"}}, {"code": "pickup", "labels": {"en": "Pickup"}}]', NULL, 6),
  ('ca-car-drive', 'cat-cars', 'drive', '{"en": "Drivetrain", "ky": "Жүргүзгүч"}', 'enum', 0, 1, NULL, '[{"code": "fwd", "labels": {"en": "FWD"}}, {"code": "rwd", "labels": {"en": "RWD"}}, {"code": "4x4", "labels": {"en": "4x4"}}]', NULL, 7),
  ('ca-car-engine', 'cat-cars', 'engine_l', '{"en": "Engine", "ky": "Кыймылдаткычтын көлөмү"}', 'number', 0, 1, 'L', NULL, NULL, 8),
  ('ca-cats-breed', 'cat-cats', 'breed', '{"en": "Breed", "ky": "Тукуму"}', 'text', 0, 1, NULL, NULL, NULL, 0),
  ('ca-cats-purpose', 'cat-cats', 'purpose', '{"en": "Listing type", "ky": "Максаты"}', 'enum', 0, 1, NULL, '[{"code": "sale", "labels": {"en": "Sale"}}, {"code": "mating", "labels": {"en": "Mating"}}]', NULL, 1),
  ('ca-cloth-gender', 'cat-clothing', 'gender', '{"en": "Gender", "ky": "Жынысы"}', 'enum', 1, 1, NULL, '[{"code": "men", "labels": {"en": "Men"}}, {"code": "women", "labels": {"en": "Women"}}, {"code": "kids", "labels": {"en": "Kids"}}, {"code": "unisex", "labels": {"en": "Unisex"}}]', NULL, 0),
  ('ca-cloth-size', 'cat-clothing', 'size', '{"en": "Size", "ky": "Өлчөмү"}', 'enum', 0, 1, NULL, '[{"code": "XS"}, {"code": "S"}, {"code": "M"}, {"code": "L"}, {"code": "XL"}, {"code": "XXL"}, {"code": "XXXL"}]', NULL, 1),
  ('ca-comm-deal', 'cat-commercial', 'deal', '{"en": "Listing type", "ky": "Бүтүм түрү"}', 'enum', 1, 1, NULL, '[{"code": "sale", "labels": {"en": "Sale"}}, {"code": "long-term-rent", "labels": {"en": "Long-term rent"}}, {"code": "daily-rent", "labels": {"en": "Daily rent"}}]', NULL, 0),
  ('ca-comm-type', 'cat-commercial', 'comm_type', '{"en": "Type", "ky": "Объекттин түрү"}', 'enum', 0, 1, NULL, '[{"code": "office", "labels": {"en": "Office"}}, {"code": "shop", "labels": {"en": "Shop"}}, {"code": "warehouse", "labels": {"en": "Warehouse"}}, {"code": "production", "labels": {"en": "Production"}}, {"code": "catering", "labels": {"en": "Catering"}}]', NULL, 1),
  ('ca-comm-area', 'cat-commercial', 'area', '{"en": "Area", "ky": "Аянты"}', 'number', 0, 1, 'm²', NULL, NULL, 2),
  ('ca-pc-kind', 'cat-computers', 'kind', '{"en": "Type", "ky": "Түрү"}', 'enum', 1, 1, NULL, '[{"code": "laptop", "labels": {"en": "Laptop"}}, {"code": "all-in-one", "labels": {"en": "All-in-One"}}, {"code": "desktop", "labels": {"en": "Desktop"}}, {"code": "components", "labels": {"en": "Components"}}]', NULL, 0),
  ('ca-pc-ram', 'cat-computers', 'ram', '{"en": "RAM", "ky": "RAM"}', 'enum', 0, 1, 'GB', '[{"code": "4"}, {"code": "8"}, {"code": "16"}, {"code": "32"}, {"code": "64"}]', NULL, 1),
  ('ca-pc-brand', 'cat-computers', 'brand', '{"en": "Brand", "ky": "Бренд"}', 'enum', 0, 1, NULL, '[{"code": "Apple"}, {"code": "Asus"}, {"code": "Acer"}, {"code": "HP"}, {"code": "Lenovo"}, {"code": "Dell"}, {"code": "MSI"}, {"code": "other", "labels": {"en": "Other"}}]', NULL, 2),
  ('ca-pc-storage', 'cat-computers', 'storage_gb', '{"en": "Storage", "ky": "Диск"}', 'int', 0, 1, 'GB', NULL, NULL, 3),
  ('ca-pc-cpu-brand', 'cat-computers', 'cpu_brand', '{"en": "CPU", "ky": "CPU"}', 'enum', 0, 1, NULL, '[{"code": "Intel"}, {"code": "AMD"}, {"code": "Apple"}, {"code": "other", "labels": {"en": "Other"}}]', NULL, 4),
  ('ca-pc-cpu-model', 'cat-computers', 'cpu_model', '{"en": "CPU model", "ky": "Процессордун модели"}', 'text', 0, 0, NULL, NULL, 'cpu_brand', 5),
  ('ca-console-brand', 'cat-consoles', 'brand', '{"en": "Brand", "ky": "Бренд"}', 'enum', 0, 1, NULL, '[{"code": "PlayStation"}, {"code": "Xbox"}, {"code": "Nintendo"}]', NULL, 0),
  ('ca-dogs-breed', 'cat-dogs', 'breed', '{"en": "Breed", "ky": "Тукуму"}', 'text', 0, 1, NULL, NULL, NULL, 0),
  ('ca-dogs-purpose', 'cat-dogs', 'purpose', '{"en": "Listing type", "ky": "Максаты"}', 'enum', 0, 1, NULL, '[{"code": "sale", "labels": {"en": "Sale"}}, {"code": "mating", "labels": {"en": "Mating"}}]', NULL, 1),
  ('ca-furn-type', 'cat-furniture', 'furn_type', '{"en": "Type", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "sofas", "labels": {"en": "Sofas"}}, {"code": "beds", "labels": {"en": "Beds"}}, {"code": "wardrobes", "labels": {"en": "Wardrobes"}}, {"code": "tables-and-chairs", "labels": {"en": "Tables & chairs"}}, {"code": "kitchens", "labels": {"en": "Kitchens"}}, {"code": "kids", "labels": {"en": "Kids"}}]', NULL, 0),
  ('ca-garage-deal', 'cat-garages', 'deal', '{"en": "Listing type", "ky": "Бүтүм түрү"}', 'enum', 1, 1, NULL, '[{"code": "sale", "labels": {"en": "Sale"}}, {"code": "long-term-rent", "labels": {"en": "Long-term rent"}}, {"code": "daily-rent", "labels": {"en": "Daily rent"}}]', NULL, 0),
  ('ca-garage-type', 'cat-garages', 'garage_type', '{"en": "Type", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "garage", "labels": {"en": "Garage"}}, {"code": "parking", "labels": {"en": "Parking"}}, {"code": "box", "labels": {"en": "Box"}}]', NULL, 1),
  ('ca-house-deal', 'cat-houses', 'deal', '{"en": "Listing type", "ky": "Бүтүм түрү"}', 'enum', 1, 1, NULL, '[{"code": "sale", "labels": {"en": "Sale"}}, {"code": "long-term-rent", "labels": {"en": "Long-term rent"}}, {"code": "daily-rent", "labels": {"en": "Daily rent"}}]', NULL, 0),
  ('ca-house-rooms', 'cat-houses', 'rooms', '{"en": "Rooms", "ky": "Бөлмө"}', 'int', 0, 1, NULL, NULL, NULL, 1),
  ('ca-house-area', 'cat-houses', 'area', '{"en": "Area", "ky": "Үйдүн аянты"}', 'number', 0, 1, 'm²', NULL, NULL, 2),
  ('ca-house-land', 'cat-houses', 'land', '{"en": "Land", "ky": "Тилкенин аянты"}', 'number', 0, 1, 'sotka', NULL, NULL, 3),
  ('ca-jew-type', 'cat-jewelry', 'acc_type', '{"en": "Type", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "watches", "labels": {"en": "Watches"}}, {"code": "jewelry", "labels": {"en": "Jewelry"}}, {"code": "bags", "labels": {"en": "Bags"}}, {"code": "glasses", "labels": {"en": "Glasses"}}, {"code": "other", "labels": {"en": "Other"}}]', NULL, 0),
  ('ca-kids-type', 'cat-kids', 'kids_type', '{"en": "Category", "ky": "Категория"}', 'enum', 0, 1, NULL, '[{"code": "strollers", "labels": {"en": "Strollers"}}, {"code": "car-seats", "labels": {"en": "Car seats"}}, {"code": "toys", "labels": {"en": "Toys"}}, {"code": "clothing", "labels": {"en": "Clothing"}}, {"code": "furniture", "labels": {"en": "Furniture"}}]', NULL, 0),
  ('ca-kids-age', 'cat-kids', 'age_group', '{"en": "Age", "ky": "Жашы"}', 'enum', 0, 1, NULL, '[{"code": "0-1", "labels": {"en": "0–1"}}, {"code": "1-3", "labels": {"en": "1–3"}}, {"code": "3-6", "labels": {"en": "3–6"}}, {"code": "6+"}]', NULL, 1),
  ('ca-land-deal', 'cat-land', 'deal', '{"en": "Listing type", "ky": "Бүтүм түрү"}', 'enum', 1, 1, NULL, '[{"code": "sale", "labels": {"en": "Sale"}}, {"code": "long-term-rent", "labels": {"en": "Long-term rent"}}, {"code": "daily-rent", "labels": {"en": "Daily rent"}}]', NULL, 0),
  ('ca-land-area', 'cat-land', 'land', '{"en": "Area", "ky": "Тилкенин аянты"}', 'number', 1, 1, 'sotka', NULL, NULL, 1),
  ('ca-land-purpose', 'cat-land', 'purpose', '{"en": "Purpose", "ky": "Багыты"}', 'enum', 0, 1, NULL, '[{"code": "residential", "labels": {"en": "Residential"}}, {"code": "agricultural", "labels": {"en": "Agricultural"}}, {"code": "commercial", "labels": {"en": "Commercial"}}]', NULL, 2),
  ('ca-moto-make', 'cat-moto', 'make', '{"en": "Make", "ky": "Марка"}', 'enum', 1, 1, NULL, '[{"code": "Honda"}, {"code": "Yamaha"}, {"code": "Suzuki"}, {"code": "Kawasaki"}, {"code": "BMW"}, {"code": "Racer"}, {"code": "Other"}]', NULL, 0),
  ('ca-moto-year', 'cat-moto', 'year', '{"en": "Year", "ky": "Чыгарылган жылы"}', 'int', 1, 1, NULL, NULL, NULL, 1),
  ('ca-moto-engine', 'cat-moto', 'engine_cc', '{"en": "Engine", "ky": "Кыймылдаткычтын көлөмү"}', 'int', 0, 1, 'cc', NULL, NULL, 2),
  ('ca-moto-type', 'cat-moto', 'type', '{"en": "Type", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "motorcycle", "labels": {"en": "Motorcycle"}}, {"code": "scooter", "labels": {"en": "Scooter"}}, {"code": "atv", "labels": {"en": "ATV"}}, {"code": "moped", "labels": {"en": "Moped"}}]', NULL, 3),
  ('ca-parts-type', 'cat-parts', 'part_type', '{"en": "Category", "ky": "Категория"}', 'enum', 0, 1, NULL, '[{"code": "wheels-and-tires", "labels": {"en": "Wheels & tires"}}, {"code": "engine", "labels": {"en": "Engine"}}, {"code": "body", "labels": {"en": "Body"}}, {"code": "electrical", "labels": {"en": "Electrical"}}, {"code": "interior", "labels": {"en": "Interior"}}, {"code": "other", "labels": {"en": "Other"}}]', NULL, 0),
  ('ca-pet-supply', 'cat-pet-supplies', 'pet_supply', '{"en": "Category", "ky": "Категория"}', 'enum', 0, 1, NULL, '[{"code": "food", "labels": {"en": "Food"}}, {"code": "accessories", "labels": {"en": "Accessories"}}, {"code": "cages-and-aquariums", "labels": {"en": "Cages & aquariums"}}, {"code": "grooming", "labels": {"en": "Grooming"}}]', NULL, 0),
  ('ca-phone-brand', 'cat-phones', 'brand', '{"en": "Brand", "ky": "Бренд"}', 'enum', 1, 1, NULL, '[{"code": "Apple"}, {"code": "Samsung"}, {"code": "Xiaomi"}, {"code": "Huawei"}, {"code": "Honor"}, {"code": "Realme"}, {"code": "OPPO"}, {"code": "Vivo"}, {"code": "Nokia"}]', NULL, 0),
  ('ca-phone-storage', 'cat-phones', 'storage', '{"en": "Storage", "ky": "Эстутум"}', 'enum', 0, 1, 'GB', '[{"code": "32"}, {"code": "64"}, {"code": "128"}, {"code": "256"}, {"code": "512"}, {"code": "1024"}]', NULL, 1),
  ('ca-phone-model', 'cat-phones', 'model', '{"en": "Model", "ky": "Модель"}', 'text', 0, 0, NULL, NULL, 'brand', 2),
  ('ca-photo-type', 'cat-photo', 'cam_type', '{"en": "Type", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "dslr", "labels": {"en": "DSLR"}}, {"code": "mirrorless", "labels": {"en": "Mirrorless"}}, {"code": "compact", "labels": {"en": "Compact"}}, {"code": "action", "labels": {"en": "Action"}}]', NULL, 0),
  ('ca-shoe-gender', 'cat-shoes', 'gender', '{"en": "Gender", "ky": "Жынысы"}', 'enum', 1, 1, NULL, '[{"code": "men", "labels": {"en": "Men"}}, {"code": "women", "labels": {"en": "Women"}}, {"code": "kids", "labels": {"en": "Kids"}}, {"code": "unisex", "labels": {"en": "Unisex"}}]', NULL, 0),
  ('ca-shoe-size', 'cat-shoes', 'shoe_size', '{"en": "Size", "ky": "Өлчөмү"}', 'int', 0, 1, NULL, NULL, NULL, 1),
  ('ca-sw-brand', 'cat-smartwatch', 'brand', '{"en": "Brand", "ky": "Бренд"}', 'enum', 0, 1, NULL, '[{"code": "Apple"}, {"code": "Samsung"}, {"code": "Xiaomi"}, {"code": "Huawei"}, {"code": "Amazfit"}, {"code": "other", "labels": {"en": "Other"}}]', NULL, 0),
  ('ca-tab-brand', 'cat-tablets', 'brand', '{"en": "Brand", "ky": "Бренд"}', 'enum', 0, 1, NULL, '[{"code": "Apple"}, {"code": "Samsung"}, {"code": "Xiaomi"}, {"code": "Huawei"}, {"code": "Lenovo"}, {"code": "other", "labels": {"en": "Other"}}]', NULL, 0),
  ('ca-tab-storage', 'cat-tablets', 'storage', '{"en": "Storage", "ky": "Эстутум"}', 'enum', 0, 1, 'GB', '[{"code": "32"}, {"code": "64"}, {"code": "128"}, {"code": "256"}, {"code": "512"}, {"code": "1024"}]', NULL, 1),
  ('ca-truck-type', 'cat-trucks', 'type', '{"en": "Type", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "truck", "labels": {"en": "Truck"}}, {"code": "bus", "labels": {"en": "Bus"}}, {"code": "machinery", "labels": {"en": "Machinery"}}, {"code": "trailer", "labels": {"en": "Trailer"}}]', NULL, 0),
  ('ca-truck-year', 'cat-trucks', 'year', '{"en": "Year", "ky": "Чыгарылган жылы"}', 'int', 0, 1, NULL, NULL, NULL, 1),
  ('ca-truck-mileage', 'cat-trucks', 'mileage', '{"en": "Mileage", "ky": "Жүрүшү"}', 'int', 0, 1, 'km', NULL, NULL, 2),
  ('ca-tv-brand', 'cat-tv', 'brand', '{"en": "Brand", "ky": "Бренд"}', 'enum', 0, 1, NULL, '[{"code": "Samsung"}, {"code": "LG"}, {"code": "Sony"}, {"code": "Xiaomi"}, {"code": "TCL"}, {"code": "other", "labels": {"en": "Other"}}]', NULL, 0),
  ('ca-tv-screen', 'cat-tv', 'screen_in', '{"en": "Screen size", "ky": "Диагональ"}', 'int', 0, 1, '"', NULL, NULL, 1),
  ('ca-tv-panel', 'cat-tv', 'panel', '{"en": "Panel", "ky": "Матрица"}', 'enum', 0, 1, NULL, '[{"code": "LED"}, {"code": "OLED"}, {"code": "QLED"}]', NULL, 2);
