-- classifieds seed — English-canonical taxonomy (codes = English slugs; labels = display).
-- Generated from frontend taxonomy/*.md (en) + ky-taxonomy.draft.json (ky). NO Russian.
-- Geo names transliterated to latin (native review welcome). Enum option KY is Phase 2.

PRAGMA foreign_keys = ON;

INSERT INTO geo_oblast (id, name, labels, sort_order) VALUES
  ('ob-bishkek', 'Bishkek', NULL, 0),
  ('ob-osh-city', 'Osh (city)', NULL, 1),
  ('ob-chuy', 'Chuy', NULL, 2),
  ('ob-osh', 'Osh', NULL, 3),
  ('ob-jalalabad', 'Jalal-Abad', NULL, 4),
  ('ob-issykkul', 'Issyk-Kul', NULL, 5),
  ('ob-naryn', 'Naryn', NULL, 6),
  ('ob-talas', 'Talas', NULL, 7),
  ('ob-batken', 'Batken', NULL, 8);

INSERT INTO geo_city (id, oblast_id, name, labels, sort_order) VALUES
  ('ci-bishkek', 'ob-bishkek', 'Bishkek', '{"ky": "Бишкек"}', 0),
  ('ci-osh', 'ob-osh-city', 'Osh', '{"ky": "Ош"}', 0),
  ('ci-tokmok', 'ob-chuy', 'Tokmok', '{"ky": "Токмок"}', 0),
  ('ci-uzgen', 'ob-osh', 'Uzgen', '{"ky": "Өзгөн"}', 0),
  ('ci-jalalabad', 'ob-jalalabad', 'Jalal-Abad', '{"ky": "Жалал-Абад"}', 0),
  ('ci-karakol', 'ob-issykkul', 'Karakol', '{"ky": "Каракол"}', 0),
  ('ci-naryn', 'ob-naryn', 'Naryn', '{"ky": "Нарын"}', 0),
  ('ci-talas', 'ob-talas', 'Talas', '{"ky": "Талас"}', 0),
  ('ci-batken', 'ob-batken', 'Batken', '{"ky": "Баткен"}', 0),
  ('ci-kara-balta', 'ob-chuy', 'Kara-Balta', '{"ky": "Кара-Балта"}', 1),
  ('ci-balykchy', 'ob-issykkul', 'Balykchy', '{"ky": "Балыкчы"}', 1),
  ('ci-kant', 'ob-chuy', 'Kant', '{"ky": "Кант"}', 2),
  ('ci-cholponata', 'ob-issykkul', 'Cholpon-Ata', '{"ky": "Чолпон-Ата"}', 2);

INSERT INTO geo_district (id, city_id, name, sort_order) VALUES
  ('di-leninsky', 'ci-bishkek', 'Leninsky', 0),
  ('di-oktyabrsky', 'ci-bishkek', 'Oktyabrsky', 1),
  ('di-pervomaysky', 'ci-bishkek', 'Pervomaysky', 2),
  ('di-sverdlovsky', 'ci-bishkek', 'Sverdlovsky', 3);

INSERT INTO category (id, parent_id, slug, name, labels, sort_order) VALUES
  ('cat-transport', NULL, 'transport', 'Transport', '{"ky": "Транспорт"}', 0),
  ('cat-realestate', NULL, 'realestate', 'Real Estate', '{"ky": "Кыймылсыз мүлк"}', 1),
  ('cat-electronics', NULL, 'electronics', 'Electronics', '{"ky": "Электроника"}', 2),
  ('cat-home', NULL, 'home', 'Home & Garden', '{"ky": "Үй жана бак"}', 3),
  ('cat-personal', NULL, 'personal', 'Personal Items', '{"ky": "Жеке буюмдар"}', 4),
  ('cat-animals', NULL, 'animals', 'Animals', '{"ky": "Жаныбарлар"}', 5),
  ('cat-jobs', NULL, 'jobs', 'Jobs', '{"ky": "Жумуш"}', 6),
  ('cat-services', NULL, 'services', 'Services', '{"ky": "Кызматтар"}', 7),
  ('cat-cars', 'cat-transport', 'cars', 'Cars', '{"ky": "Унаалар"}', 0),
  ('cat-apartments', 'cat-realestate', 'apartments', 'Apartments', '{"ky": "Батирлер"}', 0),
  ('cat-phones', 'cat-electronics', 'phones', 'Phones', '{"ky": "Телефондор"}', 0),
  ('cat-furniture', 'cat-home', 'furniture', 'Furniture', '{"ky": "Эмерек"}', 0),
  ('cat-clothing', 'cat-personal', 'clothing', 'Clothing', '{"ky": "Кийим"}', 0),
  ('cat-dogs', 'cat-animals', 'dogs', 'Dogs', '{"ky": "Иттер"}', 0),
  ('cat-moto', 'cat-transport', 'moto', 'Motorcycles', '{"ky": "Мотоциклдер"}', 1),
  ('cat-houses', 'cat-realestate', 'houses', 'Houses', '{"ky": "Үйлөр"}', 1),
  ('cat-computers', 'cat-electronics', 'computers', 'Computers', '{"ky": "Компютерлер"}', 1),
  ('cat-appliances', 'cat-home', 'appliances', 'Appliances', '{"ky": "Техника"}', 1),
  ('cat-shoes', 'cat-personal', 'shoes', 'Shoes', '{"ky": "Бут кийим"}', 1),
  ('cat-cats', 'cat-animals', 'cats', 'Cats', '{"ky": "Мышыктар"}', 1),
  ('cat-trucks', 'cat-transport', 'trucks', 'Trucks & machinery', '{"ky": "Жүк унаа"}', 2),
  ('cat-commercial', 'cat-realestate', 'commercial', 'Commercial', '{"ky": "Коммерциялык"}', 2),
  ('cat-tablets', 'cat-electronics', 'tablets', 'Tablets', '{"ky": "Планшеттер"}', 2),
  ('cat-build', 'cat-home', 'build', 'Repair & building materials', '{"ky": "Курулуш"}', 2),
  ('cat-kids', 'cat-personal', 'kids', 'Kids', '{"ky": "Балдар"}', 2),
  ('cat-birds', 'cat-animals', 'birds', 'Birds', '{"ky": "Канаттуулар"}', 2),
  ('cat-parts', 'cat-transport', 'parts', 'Parts & accessories', '{"ky": "Тетиктер"}', 3),
  ('cat-land', 'cat-realestate', 'land', 'Land', '{"ky": "Жер тилкелери"}', 3),
  ('cat-tv', 'cat-electronics', 'tv', 'TV & projectors', '{"ky": "ТВ жана проекторлор"}', 3),
  ('cat-plants', 'cat-home', 'plants', 'Plants', '{"ky": "Өсүмдүктөр"}', 3),
  ('cat-jewelry', 'cat-personal', 'jewelry', 'Watches & accessories', '{"ky": "Аксессуарлар"}', 3),
  ('cat-pets-other', 'cat-animals', 'pets-other', 'Other animals', '{"ky": "Башка жаныбарлар"}', 3),
  ('cat-garages', 'cat-realestate', 'garages', 'Garages', '{"ky": "Гараждар"}', 4),
  ('cat-audio', 'cat-electronics', 'audio', 'Audio', '{"ky": "Аудио"}', 4),
  ('cat-homeware', 'cat-home', 'homeware', 'Homeware', '{"ky": "Үй буюмдары"}', 4),
  ('cat-beauty', 'cat-personal', 'beauty', 'Beauty & health', '{"ky": "Сулуулук"}', 4),
  ('cat-pet-supplies', 'cat-animals', 'pet-supplies', 'Pet supplies', '{"ky": "Жаныбар товарлары"}', 4),
  ('cat-photo', 'cat-electronics', 'photo', 'Photo & video', '{"ky": "Фото жана видео"}', 5),
  ('cat-consoles', 'cat-electronics', 'consoles', 'Consoles', '{"ky": "Оюн консолдору"}', 6),
  ('cat-smartwatch', 'cat-electronics', 'smartwatch', 'Smartwatches', '{"ky": "Акылдуу сааттар"}', 7);

INSERT INTO category_attribute (id, category_id, key, label, labels, type, required, filterable, unit, options, depends_on, sort_order) VALUES
  ('ca-apt-deal', 'cat-apartments', 'deal', 'Listing type', '{"en": "Listing type", "ky": "Бүтүм түрү"}', 'enum', 1, 1, NULL, '[{"code": "sale", "labels": {"en": "Sale", "ky": "Сатуу"}}, {"code": "long-term-rent", "labels": {"en": "Long-term rent", "ky": "Узак ижара"}}, {"code": "daily-rent", "labels": {"en": "Daily rent", "ky": "Күндүк ижара"}}]', NULL, 0),
  ('ca-apt-rooms', 'cat-apartments', 'rooms', 'Rooms', '{"en": "Rooms", "ky": "Бөлмө"}', 'int', 1, 1, NULL, NULL, NULL, 1),
  ('ca-apt-area', 'cat-apartments', 'area', 'Area', '{"en": "Area", "ky": "Аянты"}', 'number', 0, 1, 'm²', NULL, NULL, 2),
  ('ca-apt-floor', 'cat-apartments', 'floor', 'Floor', '{"en": "Floor", "ky": "Кабат"}', 'int', 0, 1, NULL, NULL, NULL, 3),
  ('ca-apt-floors', 'cat-apartments', 'total_floors', 'Total floors', '{"en": "Total floors", "ky": "Кабаттуулугу"}', 'int', 0, 0, NULL, NULL, NULL, 4),
  ('ca-apt-furn', 'cat-apartments', 'furnished', 'Furnished', '{"en": "Furnished", "ky": "Эмерек"}', 'bool', 0, 1, NULL, NULL, NULL, 5),
  ('ca-appl-type', 'cat-appliances', 'appliance_type', 'Type', '{"en": "Type", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "refrigerators", "labels": {"en": "Refrigerators", "ky": "Муздаткыч"}}, {"code": "washers", "labels": {"en": "Washers", "ky": "Кир жуугуч"}}, {"code": "stoves", "labels": {"en": "Stoves", "ky": "Плита"}}, {"code": "dishwashers", "labels": {"en": "Dishwashers", "ky": "Идиш жуугуч"}}, {"code": "microwaves", "labels": {"en": "Microwaves", "ky": "Микротолкун"}}, {"code": "air-conditioners", "labels": {"en": "Air conditioners", "ky": "Кондиционер"}}, {"code": "vacuums", "labels": {"en": "Vacuums", "ky": "Чаңсоргуч"}}]', NULL, 0),
  ('ca-audio-type', 'cat-audio', 'audio_type', 'Type', '{"en": "Type", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "headphones", "labels": {"en": "Headphones", "ky": "Кулакчындар"}}, {"code": "speakers", "labels": {"en": "Speakers", "ky": "Колонкалар"}}, {"code": "soundbar", "labels": {"en": "Soundbar", "ky": "Soundbar"}}, {"code": "microphones", "labels": {"en": "Microphones", "ky": "Микрофондор"}}]', NULL, 0),
  ('ca-birds-breed', 'cat-birds', 'breed', 'Species', '{"en": "Species", "ky": "Түрү"}', 'text', 0, 1, NULL, NULL, NULL, 0),
  ('ca-build-type', 'cat-build', 'build_type', 'Category', '{"en": "Category", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "tools", "labels": {"en": "Tools", "ky": "Аспаптар"}}, {"code": "building-materials", "labels": {"en": "Building materials", "ky": "Курулуш материалдары"}}, {"code": "plumbing", "labels": {"en": "Plumbing", "ky": "Сантехника"}}, {"code": "electrical", "labels": {"en": "Electrical", "ky": "Электрика"}}, {"code": "doors-and-windows", "labels": {"en": "Doors & windows", "ky": "Эшик-терезе"}}]', NULL, 0),
  ('ca-car-make', 'cat-cars', 'make', 'Make', '{"en": "Make", "ky": "Марка"}', 'enum', 1, 1, NULL, '[{"code": "Toyota"}, {"code": "Honda"}, {"code": "Nissan"}, {"code": "Mercedes-Benz"}, {"code": "BMW"}, {"code": "Audi"}, {"code": "Lexus"}, {"code": "Hyundai"}, {"code": "Kia"}, {"code": "Lada"}, {"code": "Mitsubishi"}, {"code": "Volkswagen"}]', NULL, 0),
  ('ca-car-model', 'cat-cars', 'model', 'Model', '{"en": "Model", "ky": "Модел"}', 'text', 0, 1, NULL, NULL, 'make', 1),
  ('ca-car-year', 'cat-cars', 'year', 'Year', '{"en": "Year", "ky": "Жылы"}', 'int', 1, 1, NULL, NULL, NULL, 2),
  ('ca-car-mileage', 'cat-cars', 'mileage', 'Mileage', '{"en": "Mileage", "ky": "Жүрүшү"}', 'int', 0, 1, 'km', NULL, NULL, 3),
  ('ca-car-trans', 'cat-cars', 'transmission', 'Transmission', '{"en": "Transmission", "ky": "Трансмиссия"}', 'enum', 0, 1, NULL, '[{"code": "manual", "labels": {"en": "Manual", "ky": "Механика"}}, {"code": "automatic", "labels": {"en": "Automatic", "ky": "Автомат"}}, {"code": "cvt", "labels": {"en": "CVT", "ky": "Вариатор"}}, {"code": "amt", "labels": {"en": "AMT", "ky": "Робот"}}]', NULL, 4),
  ('ca-car-fuel', 'cat-cars', 'fuel', 'Fuel', '{"en": "Fuel", "ky": "Отун"}', 'enum', 0, 1, NULL, '[{"code": "petrol", "labels": {"en": "Petrol", "ky": "Бензин"}}, {"code": "diesel", "labels": {"en": "Diesel", "ky": "Дизел"}}, {"code": "lpg", "labels": {"en": "Gas", "ky": "Газ"}}, {"code": "hybrid", "labels": {"en": "Hybrid", "ky": "Гибрид"}}, {"code": "electric", "labels": {"en": "Electric", "ky": "Электр"}}]', NULL, 5),
  ('ca-car-body', 'cat-cars', 'body', 'Body type', '{"en": "Body type", "ky": "Денеси"}', 'enum', 0, 1, NULL, '[{"code": "sedan", "labels": {"en": "Sedan", "ky": "Sedan"}}, {"code": "hatchback", "labels": {"en": "Hatchback", "ky": "Hatchback"}}, {"code": "wagon", "labels": {"en": "Wagon", "ky": "Wagon"}}, {"code": "suv", "labels": {"en": "SUV", "ky": "SUV"}}, {"code": "minivan", "labels": {"en": "Minivan", "ky": "Minivan"}}, {"code": "coupe", "labels": {"en": "Coupe", "ky": "Coupe"}}, {"code": "pickup", "labels": {"en": "Pickup", "ky": "Pickup"}}]', NULL, 6),
  ('ca-car-drive', 'cat-cars', 'drive', 'Drivetrain', '{"en": "Drivetrain", "ky": "Жетек"}', 'enum', 0, 1, NULL, '[{"code": "fwd", "labels": {"en": "FWD", "ky": "FWD (Алдыңкы)"}}, {"code": "rwd", "labels": {"en": "RWD", "ky": "RWD (Арткы)"}}, {"code": "4x4", "labels": {"en": "4x4", "ky": "4x4 (Толук)"}}]', NULL, 7),
  ('ca-car-engine', 'cat-cars', 'engine_l', 'Engine', '{"en": "Engine", "ky": "Мотор"}', 'number', 0, 1, 'L', NULL, NULL, 8),
  ('ca-cats-breed', 'cat-cats', 'breed', 'Breed', '{"en": "Breed", "ky": "Тукуму"}', 'text', 0, 1, NULL, NULL, NULL, 0),
  ('ca-cats-purpose', 'cat-cats', 'purpose', 'Listing type', '{"en": "Listing type", "ky": "Максаты"}', 'enum', 0, 1, NULL, '[{"code": "sale", "labels": {"en": "Sale", "ky": "Сатуу"}}, {"code": "mating", "labels": {"en": "Mating", "ky": "Каптатуу"}}]', NULL, 1),
  ('ca-cloth-gender', 'cat-clothing', 'gender', 'Gender', '{"en": "Gender", "ky": "Жынысы"}', 'enum', 1, 1, NULL, '[{"code": "men", "labels": {"en": "Men", "ky": "Эркек"}}, {"code": "women", "labels": {"en": "Women", "ky": "Аял"}}, {"code": "kids", "labels": {"en": "Kids", "ky": "Балдар"}}, {"code": "unisex", "labels": {"en": "Unisex", "ky": "Унисекс"}}]', NULL, 0),
  ('ca-cloth-size', 'cat-clothing', 'size', 'Size', '{"en": "Size", "ky": "Size"}', 'enum', 0, 1, NULL, '[{"code": "XS"}, {"code": "S"}, {"code": "M"}, {"code": "L"}, {"code": "XL"}, {"code": "XXL"}, {"code": "XXXL"}]', NULL, 1),
  ('ca-comm-deal', 'cat-commercial', 'deal', 'Listing type', '{"en": "Listing type", "ky": "Бүтүм түрү"}', 'enum', 1, 1, NULL, '[{"code": "sale", "labels": {"en": "Sale", "ky": "Сатуу"}}, {"code": "long-term-rent", "labels": {"en": "Long-term rent", "ky": "Узак ижара"}}, {"code": "daily-rent", "labels": {"en": "Daily rent", "ky": "Күндүк ижара"}}]', NULL, 0),
  ('ca-comm-type', 'cat-commercial', 'comm_type', 'Type', '{"en": "Type", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "office", "labels": {"en": "Office", "ky": "Офис"}}, {"code": "shop", "labels": {"en": "Shop", "ky": "Дүкөн"}}, {"code": "warehouse", "labels": {"en": "Warehouse", "ky": "Кампа"}}, {"code": "production", "labels": {"en": "Production", "ky": "Өндүрүш"}}, {"code": "catering", "labels": {"en": "Catering", "ky": "Коомдук тамактануу"}}]', NULL, 1),
  ('ca-comm-area', 'cat-commercial', 'area', 'Area', '{"en": "Area", "ky": "Аянты"}', 'number', 0, 1, 'm²', NULL, NULL, 2),
  ('ca-pc-kind', 'cat-computers', 'kind', 'Type', '{"en": "Type", "ky": "Түрү"}', 'enum', 1, 1, NULL, '[{"code": "laptop", "labels": {"en": "Laptop", "ky": "Laptop"}}, {"code": "all-in-one", "labels": {"en": "All-in-One", "ky": "All-in-One"}}, {"code": "desktop", "labels": {"en": "Desktop", "ky": "Desktop"}}, {"code": "components", "labels": {"en": "Components", "ky": "Components"}}]', NULL, 0),
  ('ca-pc-ram', 'cat-computers', 'ram', 'RAM', '{"en": "RAM", "ky": "RAM"}', 'enum', 0, 1, 'GB', '[{"code": "4"}, {"code": "8"}, {"code": "16"}, {"code": "32"}, {"code": "64"}]', NULL, 1),
  ('ca-pc-brand', 'cat-computers', 'brand', 'Brand', '{"en": "Brand", "ky": "Бренд"}', 'enum', 0, 1, NULL, '[{"code": "Apple"}, {"code": "Asus"}, {"code": "Acer"}, {"code": "HP"}, {"code": "Lenovo"}, {"code": "Dell"}, {"code": "MSI"}, {"code": "other", "labels": {"en": "Other", "ky": "Башка"}}]', NULL, 2),
  ('ca-pc-storage', 'cat-computers', 'storage_gb', 'Storage', '{"en": "Storage", "ky": "Storage"}', 'int', 0, 1, 'GB', NULL, NULL, 3),
  ('ca-pc-cpu-brand', 'cat-computers', 'cpu_brand', 'CPU', '{"en": "CPU", "ky": "CPU"}', 'enum', 0, 1, NULL, '[{"code": "Intel"}, {"code": "AMD"}, {"code": "Apple"}, {"code": "other", "labels": {"en": "Other", "ky": "Башка"}}]', NULL, 4),
  ('ca-pc-cpu-model', 'cat-computers', 'cpu_model', 'CPU model', '{"en": "CPU model", "ky": "CPU model"}', 'text', 0, 0, NULL, NULL, 'cpu_brand', 5),
  ('ca-console-brand', 'cat-consoles', 'brand', 'Brand', '{"en": "Brand", "ky": "Бренд"}', 'enum', 0, 1, NULL, '[{"code": "PlayStation"}, {"code": "Xbox"}, {"code": "Nintendo"}]', NULL, 0),
  ('ca-dogs-breed', 'cat-dogs', 'breed', 'Breed', '{"en": "Breed", "ky": "Тукуму"}', 'text', 0, 1, NULL, NULL, NULL, 0),
  ('ca-dogs-purpose', 'cat-dogs', 'purpose', 'Listing type', '{"en": "Listing type", "ky": "Максаты"}', 'enum', 0, 1, NULL, '[{"code": "sale", "labels": {"en": "Sale", "ky": "Сатуу"}}, {"code": "mating", "labels": {"en": "Mating", "ky": "Каптатуу"}}]', NULL, 1),
  ('ca-furn-type', 'cat-furniture', 'furn_type', 'Type', '{"en": "Type", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "sofas", "labels": {"en": "Sofas", "ky": "Дивандар"}}, {"code": "beds", "labels": {"en": "Beds", "ky": "Керебеттер"}}, {"code": "wardrobes", "labels": {"en": "Wardrobes", "ky": "Шкафтар"}}, {"code": "tables-and-chairs", "labels": {"en": "Tables & chairs", "ky": "Стол-орундук"}}, {"code": "kitchens", "labels": {"en": "Kitchens", "ky": "Ашкана"}}, {"code": "kids", "labels": {"en": "Kids", "ky": "Балдар"}}]', NULL, 0),
  ('ca-garage-deal', 'cat-garages', 'deal', 'Listing type', '{"en": "Listing type", "ky": "Бүтүм түрү"}', 'enum', 1, 1, NULL, '[{"code": "sale", "labels": {"en": "Sale", "ky": "Сатуу"}}, {"code": "long-term-rent", "labels": {"en": "Long-term rent", "ky": "Узак ижара"}}, {"code": "daily-rent", "labels": {"en": "Daily rent", "ky": "Күндүк ижара"}}]', NULL, 0),
  ('ca-garage-type', 'cat-garages', 'garage_type', 'Type', '{"en": "Type", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "garage", "labels": {"en": "Garage", "ky": "Гараж"}}, {"code": "parking", "labels": {"en": "Parking", "ky": "Паркинг"}}, {"code": "box", "labels": {"en": "Box", "ky": "Бокс"}}]', NULL, 1),
  ('ca-house-deal', 'cat-houses', 'deal', 'Listing type', '{"en": "Listing type", "ky": "Бүтүм түрү"}', 'enum', 1, 1, NULL, '[{"code": "sale", "labels": {"en": "Sale", "ky": "Сатуу"}}, {"code": "long-term-rent", "labels": {"en": "Long-term rent", "ky": "Узак ижара"}}, {"code": "daily-rent", "labels": {"en": "Daily rent", "ky": "Күндүк ижара"}}]', NULL, 0),
  ('ca-house-rooms', 'cat-houses', 'rooms', 'Rooms', '{"en": "Rooms", "ky": "Бөлмө"}', 'int', 0, 1, NULL, NULL, NULL, 1),
  ('ca-house-area', 'cat-houses', 'area', 'Area', '{"en": "Area", "ky": "Аянты"}', 'number', 0, 1, 'm²', NULL, NULL, 2),
  ('ca-house-land', 'cat-houses', 'land', 'Land', '{"en": "Land", "ky": "Тилке"}', 'number', 0, 1, 'sotka', NULL, NULL, 3),
  ('ca-jew-type', 'cat-jewelry', 'acc_type', 'Type', '{"en": "Type", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "watches", "labels": {"en": "Watches", "ky": "Саат"}}, {"code": "jewelry", "labels": {"en": "Jewelry", "ky": "Зер буюм"}}, {"code": "bags", "labels": {"en": "Bags", "ky": "Сумка"}}, {"code": "glasses", "labels": {"en": "Glasses", "ky": "Көз айнек"}}, {"code": "other", "labels": {"en": "Other", "ky": "Башка"}}]', NULL, 0),
  ('ca-kids-type', 'cat-kids', 'kids_type', 'Category', '{"en": "Category", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "strollers", "labels": {"en": "Strollers", "ky": "Коляска"}}, {"code": "car-seats", "labels": {"en": "Car seats", "ky": "Автоорундук"}}, {"code": "toys", "labels": {"en": "Toys", "ky": "Оюнчук"}}, {"code": "clothing", "labels": {"en": "Clothing", "ky": "Кийим"}}, {"code": "furniture", "labels": {"en": "Furniture", "ky": "Эмерек"}}]', NULL, 0),
  ('ca-kids-age', 'cat-kids', 'age_group', 'Age', '{"en": "Age", "ky": "Жашы"}', 'enum', 0, 1, NULL, '[{"code": "0-1", "labels": {"en": "0–1", "ky": "0–1"}}, {"code": "1-3", "labels": {"en": "1–3", "ky": "1–3"}}, {"code": "3-6", "labels": {"en": "3–6", "ky": "3–6"}}, {"code": "6+"}]', NULL, 1),
  ('ca-land-deal', 'cat-land', 'deal', 'Listing type', '{"en": "Listing type", "ky": "Бүтүм түрү"}', 'enum', 1, 1, NULL, '[{"code": "sale", "labels": {"en": "Sale", "ky": "Сатуу"}}, {"code": "long-term-rent", "labels": {"en": "Long-term rent", "ky": "Узак ижара"}}, {"code": "daily-rent", "labels": {"en": "Daily rent", "ky": "Күндүк ижара"}}]', NULL, 0),
  ('ca-land-area', 'cat-land', 'land', 'Area', '{"en": "Area", "ky": "Аянты"}', 'number', 1, 1, 'sotka', NULL, NULL, 1),
  ('ca-land-purpose', 'cat-land', 'purpose', 'Purpose', '{"en": "Purpose", "ky": "Багыты"}', 'enum', 0, 1, NULL, '[{"code": "residential", "labels": {"en": "Residential", "ky": "Турак жай"}}, {"code": "agricultural", "labels": {"en": "Agricultural", "ky": "Айыл чарба"}}, {"code": "commercial", "labels": {"en": "Commercial", "ky": "Коммерциялык"}}]', NULL, 2),
  ('ca-moto-make', 'cat-moto', 'make', 'Make', '{"en": "Make", "ky": "Марка"}', 'enum', 1, 1, NULL, '[{"code": "Honda"}, {"code": "Yamaha"}, {"code": "Suzuki"}, {"code": "Kawasaki"}, {"code": "BMW"}, {"code": "Racer"}, {"code": "Other", "labels": {"en": "Other", "ky": "Башка"}}]', NULL, 0),
  ('ca-moto-year', 'cat-moto', 'year', 'Year', '{"en": "Year", "ky": "Жылы"}', 'int', 1, 1, NULL, NULL, NULL, 1),
  ('ca-moto-engine', 'cat-moto', 'engine_cc', 'Engine', '{"en": "Engine", "ky": "Мотор"}', 'int', 0, 1, 'cc', NULL, NULL, 2),
  ('ca-moto-type', 'cat-moto', 'type', 'Type', '{"en": "Type", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "motorcycle", "labels": {"en": "Motorcycle", "ky": "Мотоцикл"}}, {"code": "scooter", "labels": {"en": "Scooter", "ky": "Скутер"}}, {"code": "atv", "labels": {"en": "ATV", "ky": "ATV"}}, {"code": "moped", "labels": {"en": "Moped", "ky": "Мопед"}}]', NULL, 3),
  ('ca-parts-type', 'cat-parts', 'part_type', 'Category', '{"en": "Category", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "wheels-and-tires", "labels": {"en": "Wheels & tires", "ky": "Дөңгөлөктөр"}}, {"code": "engine", "labels": {"en": "Engine", "ky": "Мотор"}}, {"code": "body", "labels": {"en": "Body", "ky": "Кузов бөлүктөрү"}}, {"code": "electrical", "labels": {"en": "Electrical", "ky": "Электрика"}}, {"code": "interior", "labels": {"en": "Interior", "ky": "Салон"}}, {"code": "other", "labels": {"en": "Other", "ky": "Башка"}}]', NULL, 0),
  ('ca-pet-supply', 'cat-pet-supplies', 'pet_supply', 'Category', '{"en": "Category", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "food", "labels": {"en": "Food", "ky": "Тоют"}}, {"code": "accessories", "labels": {"en": "Accessories", "ky": "Аксессуар"}}, {"code": "cages-and-aquariums", "labels": {"en": "Cages & aquariums", "ky": "Тор жана аквариум"}}, {"code": "grooming", "labels": {"en": "Grooming", "ky": "Күтүм"}}]', NULL, 0),
  ('ca-phone-brand', 'cat-phones', 'brand', 'Brand', '{"en": "Brand", "ky": "Бренд"}', 'enum', 1, 1, NULL, '[{"code": "Apple"}, {"code": "Samsung"}, {"code": "Xiaomi"}, {"code": "Huawei"}, {"code": "Honor"}, {"code": "Realme"}, {"code": "OPPO"}, {"code": "Vivo"}, {"code": "Nokia"}]', NULL, 0),
  ('ca-phone-storage', 'cat-phones', 'storage', 'Storage', '{"en": "Storage", "ky": "Storage"}', 'enum', 0, 1, 'GB', '[{"code": "32"}, {"code": "64"}, {"code": "128"}, {"code": "256"}, {"code": "512"}, {"code": "1024"}]', NULL, 1),
  ('ca-phone-model', 'cat-phones', 'model', 'Model', '{"en": "Model", "ky": "Модел"}', 'text', 0, 0, NULL, NULL, 'brand', 2),
  ('ca-photo-type', 'cat-photo', 'cam_type', 'Type', '{"en": "Type", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "dslr", "labels": {"en": "DSLR", "ky": "DSLR"}}, {"code": "mirrorless", "labels": {"en": "Mirrorless", "ky": "Mirrorless"}}, {"code": "compact", "labels": {"en": "Compact", "ky": "Compact"}}, {"code": "action", "labels": {"en": "Action", "ky": "Action"}}]', NULL, 0),
  ('ca-shoe-gender', 'cat-shoes', 'gender', 'Gender', '{"en": "Gender", "ky": "Жынысы"}', 'enum', 1, 1, NULL, '[{"code": "men", "labels": {"en": "Men", "ky": "Эркек"}}, {"code": "women", "labels": {"en": "Women", "ky": "Аял"}}, {"code": "kids", "labels": {"en": "Kids", "ky": "Балдар"}}, {"code": "unisex", "labels": {"en": "Unisex", "ky": "Унисекс"}}]', NULL, 0),
  ('ca-shoe-size', 'cat-shoes', 'shoe_size', 'Size', '{"en": "Size", "ky": "Өлчөмү"}', 'int', 0, 1, NULL, NULL, NULL, 1),
  ('ca-sw-brand', 'cat-smartwatch', 'brand', 'Brand', '{"en": "Brand", "ky": "Бренд"}', 'enum', 0, 1, NULL, '[{"code": "Apple"}, {"code": "Samsung"}, {"code": "Xiaomi"}, {"code": "Huawei"}, {"code": "Amazfit"}, {"code": "other", "labels": {"en": "Other", "ky": "Башка"}}]', NULL, 0),
  ('ca-tab-brand', 'cat-tablets', 'brand', 'Brand', '{"en": "Brand", "ky": "Бренд"}', 'enum', 0, 1, NULL, '[{"code": "Apple"}, {"code": "Samsung"}, {"code": "Xiaomi"}, {"code": "Huawei"}, {"code": "Lenovo"}, {"code": "other", "labels": {"en": "Other", "ky": "Башка"}}]', NULL, 0),
  ('ca-tab-storage', 'cat-tablets', 'storage', 'Storage', '{"en": "Storage", "ky": "Storage"}', 'enum', 0, 1, 'GB', '[{"code": "32"}, {"code": "64"}, {"code": "128"}, {"code": "256"}, {"code": "512"}, {"code": "1024"}]', NULL, 1),
  ('ca-truck-type', 'cat-trucks', 'type', 'Type', '{"en": "Type", "ky": "Түрү"}', 'enum', 0, 1, NULL, '[{"code": "truck", "labels": {"en": "Truck", "ky": "Жүк унаа"}}, {"code": "bus", "labels": {"en": "Bus", "ky": "Автобус"}}, {"code": "machinery", "labels": {"en": "Machinery", "ky": "Техника"}}, {"code": "trailer", "labels": {"en": "Trailer", "ky": "Чиркегич"}}]', NULL, 0),
  ('ca-truck-year', 'cat-trucks', 'year', 'Year', '{"en": "Year", "ky": "Жылы"}', 'int', 0, 1, NULL, NULL, NULL, 1),
  ('ca-truck-mileage', 'cat-trucks', 'mileage', 'Mileage', '{"en": "Mileage", "ky": "Жүрүшү"}', 'int', 0, 1, 'km', NULL, NULL, 2),
  ('ca-tv-brand', 'cat-tv', 'brand', 'Brand', '{"en": "Brand", "ky": "Бренд"}', 'enum', 0, 1, NULL, '[{"code": "Samsung"}, {"code": "LG"}, {"code": "Sony"}, {"code": "Xiaomi"}, {"code": "TCL"}, {"code": "other", "labels": {"en": "Other", "ky": "Башка"}}]', NULL, 0),
  ('ca-tv-screen', 'cat-tv', 'screen_in', 'Screen size', '{"en": "Screen size", "ky": "Диагонал"}', 'int', 0, 1, '"', NULL, NULL, 1),
  ('ca-tv-panel', 'cat-tv', 'panel', 'Panel', '{"en": "Panel", "ky": "Panel"}', 'enum', 0, 1, NULL, '[{"code": "LED"}, {"code": "OLED"}, {"code": "QLED"}]', NULL, 2);
