#!/usr/bin/env python3
"""Boot a cellar server, run a test script against it, tear it down.

Usage: run_with_server.py <cellar_binary> <test_script.py>

Picks a free port, seeds an admin, waits for the listener, runs
  python3 <test_script.py> ws://127.0.0.1:<port>/
and forwards the script's exit code. Dumps the server log on failure.
"""
import os, sys, socket, subprocess, time, tempfile, sqlite3, shutil

# A uuid4-shaped text id, generated by SQLite itself on INSERT — the SQLite
# analogue of Postgres' `gen_random_uuid()` default (the engine inserts only the
# client/scope columns and relies on the column DEFAULT to mint the primary key).
UUID4_DEFAULT = (
    "lower(hex(randomblob(4)))||'-'||lower(hex(randomblob(2)))||'-4'||"
    "substr(lower(hex(randomblob(2))),2)||'-'||substr('89ab',abs(random())%4+1,1)||"
    "substr(lower(hex(randomblob(2))),2)||'-'||lower(hex(randomblob(6)))")

def make_app_db():
    """Create a throwaway per-app SQLite database seeded with the demo product
    catalog the server-boot tests exercise (the engine applies the cel_* identity
    schema itself). The declared column types (UUID/NUMERIC/INTEGER/BOOLEAN) drive
    the catalog's type inference; the UUID primary keys auto-generate on INSERT.
    Returns (dir, db_path)."""
    d = tempfile.mkdtemp(prefix="cellar-app-")
    con = sqlite3.connect(os.path.join(d, "data.db"))
    con.executescript(f"""
        CREATE TABLE categories (
            id          UUID PRIMARY KEY DEFAULT ({UUID4_DEFAULT}),
            name        TEXT NOT NULL,
            description TEXT
        );
        CREATE TABLE products (
            id          UUID PRIMARY KEY DEFAULT ({UUID4_DEFAULT}),
            name        TEXT NOT NULL,
            sku         TEXT UNIQUE,
            price       NUMERIC,
            in_stock    INTEGER,
            is_active   BOOLEAN DEFAULT 1,
            category_id UUID REFERENCES categories(id)
        );
        CREATE TABLE notes (
            id       UUID PRIMARY KEY DEFAULT ({UUID4_DEFAULT}),
            owner_id UUID,
            title    TEXT,
            body     TEXT
        );
        -- A syncable table (offline-first sync Slice 0): carries rev + deleted, so
        -- the engine stamps rev / soft-deletes it. Empty so the sync test counts
        -- rev deterministically from 1. Inert for every other test.
        CREATE TABLE items (
            id       UUID PRIMARY KEY DEFAULT ({UUID4_DEFAULT}),
            name     TEXT NOT NULL,
            rev      INTEGER NOT NULL DEFAULT 0,
            deleted  INTEGER NOT NULL DEFAULT 0
        );
        -- A syncable CHILD of items with ON DELETE CASCADE — exercises cascade
        -- soft-delete and its realtime fan-out (sync_realtime_test). Inert elsewhere.
        CREATE TABLE item_lines (
            id       UUID PRIMARY KEY DEFAULT ({UUID4_DEFAULT}),
            item_id  UUID NOT NULL REFERENCES items(id) ON DELETE CASCADE,
            label    TEXT,
            rev      INTEGER NOT NULL DEFAULT 0,
            deleted  INTEGER NOT NULL DEFAULT 0
        );
        -- Two categories (smoke/rest assert categories count == 2).
        INSERT INTO categories (name, description) VALUES
            ('Drinks', 'Beverages'),
            ('Snacks', 'Munchies');
        -- Three products; exactly two with in_stock > 200, Cola priced above Water
        -- (smoke/rest filter in_stock>200 + order=-price -> [Cola, Water]).
        INSERT INTO products (name, sku, price, in_stock) VALUES
            ('Cola 330ml',  'COLA-330',  2.50, 500),
            ('Water 500ml', 'WATER-500', 1.00, 300),
            ('Chips 100g',  'CHIPS-100', 3.00,  40);
    """)
    con.commit()
    con.close()
    # A bundle hooks.lua. CEL_HOOKS_FILE overrides it (the CRUD-hook test points it
    # at a before/authorize/after bundle); the default below defines only rpc, so
    # it's inert for every other test (no before/authorize/after).
    custom = os.environ.get("CEL_HOOKS_FILE")
    if custom:
        with open(custom) as src, open(os.path.join(d, "hooks.lua"), "w") as h:
            h.write(src.read())
        return d, os.path.join(d, "data.db")
    with open(os.path.join(d, "hooks.lua"), "w") as h:
        h.write(
            "function rpc(name, args, who)\n"
            "  if name == 'ping' then return { pong = true } end\n"
            "  if name == 'whoami' then return { role = who.role, auth = who.authenticated } end\n"
            "  if name == 'echo' then return { got = args.msg } end\n"
            "  if name == 'count_products' then\n"
            "    local rows = cellar.query('SELECT count(*) AS n FROM products')\n"
            "    return { n = rows[1].n }\n"
            "  end\n"
            "  if name == 'add_product' then\n"
            "    cellar.exec('INSERT INTO products(name, sku, price) VALUES (?, ?, ?)',\n"
            "                { args.name, args.sku, args.price })\n"
            "    return { ok = true }\n"
            "  end\n"
            "  if name == 'boom' then error('intentional hook fault') end\n"
            "  return nil, 'unknown rpc: ' .. name\n"
            "end\n")
    return d, os.path.join(d, "data.db")

def free_port():
    s = socket.socket(); s.bind(("127.0.0.1", 0))
    p = s.getsockname()[1]; s.close(); return p

def wait_listen(port, proc, timeout=8.0):
    deadline = time.time() + timeout
    while time.time() < deadline:
        if proc.poll() is not None:
            return False
        with socket.socket() as s:
            s.settimeout(0.25)
            try:
                s.connect(("127.0.0.1", port)); return True
            except OSError:
                time.sleep(0.05)
    return False

def main():
    if len(sys.argv) < 3:
        print("usage: run_with_server.py <binary> <test_script>", file=sys.stderr)
        return 2
    binary, script = sys.argv[1], sys.argv[2]
    port = free_port()
    app_dir, app_db = make_app_db()

    env = dict(os.environ)
    env.update(
        CEL_PORT=str(port),
        CEL_LOG_LEVEL=env.get("CEL_LOG_LEVEL", "warn"),
        CEL_DATA_DB=env.get("CEL_DATA_DB", app_db),
        # Seed users per role (two editors, to exercise row-level ownership).
        CEL_SEED_USERS=env.get("CEL_SEED_USERS",
            "admin@cellar.dev:s3cret-admin:admin;"
            "editor@cellar.dev:editor-pw:editor;"
            "editor2@cellar.dev:editor2-pw:editor;"
            "viewer@cellar.dev:viewer-pw:viewer"),
        # Policy overrides (row-level ownership for `notes`).
        CEL_POLICY_FILE=env.get("CEL_POLICY_FILE",
            os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                         "config", "policies.json")),
        CEL_TEST_EMAIL=env.get("CEL_TEST_EMAIL", "admin@cellar.dev"),
        CEL_TEST_PASSWORD=env.get("CEL_TEST_PASSWORD", "s3cret-admin"),
        # Disable the auth rate limiter by default so functional tests can log in
        # / register freely; the dedicated rate-limit test overrides this.
        CEL_AUTH_RATELIMIT=env.get("CEL_AUTH_RATELIMIT", "0"),
    )

    log = tempfile.NamedTemporaryFile(prefix="cellar-", suffix=".log", delete=False)
    proc = subprocess.Popen([binary], env=env, stdout=log, stderr=subprocess.STDOUT)
    try:
        if not wait_listen(port, proc):
            print(f"server failed to listen on :{port}", file=sys.stderr)
            log.flush()
            sys.stderr.write(open(log.name).read())
            return 1
        runner = ["node"] if script.endswith((".mjs", ".js")) else [sys.executable]
        rc = subprocess.call(runner + [script, f"ws://127.0.0.1:{port}/"], env=env)
    finally:
        proc.terminate()
        try: proc.wait(timeout=5)
        except subprocess.TimeoutExpired: proc.kill()
        log.flush()

    if rc != 0:
        sys.stderr.write("\n----- server log -----\n")
        sys.stderr.write(open(log.name).read())
    os.unlink(log.name)
    shutil.rmtree(app_dir, ignore_errors=True)
    return rc

if __name__ == "__main__":
    sys.exit(main())
